#서버 포트 설정
#server:
#  port: 8082

#database 연동 설정
spring:
  datasource:
    url: jdbc:mysql://3.24.175.130:3306/vital_routes_DB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: joohan
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create # 최초 생성 후 update로 바꿔주는게 data를 보호할 수 있다.
      #ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect