spring:
  datasource:
    #url: ENC(jO49RGHnkCNy+rqEKuRQ4du128xO/FGprtYMt5NCX0iNdSjOFsbOCY/h/hSWLBPbKUa0zp2gAIFhYBsNShkXCgJw05bgcInPTm47U3/FqH7yBwWuOSVXNzhhmM6CxYTzhMKyPlGjOKo8VDafXIP1qwjM/DtXjLpi)
    #username: ENC(WXJRUma8h4Aa17BMomL3Vw==)
    #password: ENC(ep1lvgJv5L9UAVQJQQW/Zg==)
    url: jdbc:mysql://3.24.175.130:3306/vital_routes_DB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: joohan
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create # 최초 생성 후 update로 바꿔주는게 data를 보호할 수 있다.
      #ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

cloud:
  aws:
    s3:
      bucket: vital-routes-bucket
    credentials:
      access-key: ENC(2UXJ1AxBkq3TG2fwyJCs1vLw+/WrHm8AajRtFc2rwlA=)
      secret-key: ENC(oaAgrjsbeLI9IIbNywgyUKqhytarQldrn6NcS+W/c2xQpVfydNgE+cCoKMxAquR4TRQQ0SPHHd8=)
      instanceProfile: true
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


jwt:
  secretKey: ENC(m3IxdMw3rZhPueIyGSClgkAQOviME+/yA6S+AETPaarWVD2ovNemTeLn1KfHGDSH9eEcX7BlprKJa4ew4W3gT+ixH9R6JPqOVc2WUVOYOOSNGP4I6ANgEA==)

kakao:
  login:
    client-id: ENC(DINFbAY/RI0maEuCPDXuQcCQNp4+CxtI7O+wFoDI1ohNpHMAWvKNo71lDMLPaAy3)
    redirect-uri: ENC(io/BNG3FIRVo5Elr8qJvP26KazkACWMxO9keK11My/JZZ1jUrvAcvHwAIhuV1j+J)
    #redirect-uri: http://localhost:8080/kakaologin
    #redirect-uri: http://localhost:8080/oauth2/kakao